glenn:
    lib: '/usr/local/torque-2.4.10/lib/libtorque.so'
    server: 'opt-batch.osc.edu'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-2.4.10/lib:$LD_LIBRARY_PATH /usr/local/torque-2.4.10/bin/qsub'
oakley:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'oak-batch.osc.edu'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH /usr/local/torque-4.2.8/bin/qsub'
ruby:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'ruby-batch.ten.osc.edu'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH /usr/local/torque-4.2.8/bin/qsub'
oxymoron:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'oak-batch.osc.edu:17001'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH /usr/local/torque-4.2.8/bin/qsub'
quick:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'quick-batch.osc.edu'
    qsub: 'LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH /usr/local/torque-4.2.8/bin/qsub'
