glenn:
    lib: '/usr/local/torque-2.4.10/lib/libtorque.so'
    server: 'opt-batch.osc.edu'
    cmd_prefix: 'PATH=/usr/local/torque-2.4.10/bin:$PATH LD_LIBRARY_PATH=/usr/local/torque-2.4.10/lib:$LD_LIBRARY_PATH'
oakley:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'oak-batch.osc.edu'
    cmd_prefix: 'PATH=/usr/local/torque-4.2.8/bin:$PATH LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH'
ruby:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'ruby-batch.ten.osc.edu'
    cmd_prefix: 'PATH=/usr/local/torque-4.2.8/bin:$PATH LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH'
oxymoron:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'oak-batch.osc.edu:17001'
    cmd_prefix: 'PATH=/usr/local/torque-4.2.8/bin:$PATH LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH'
quick:
    lib: '/usr/local/torque-4.2.8/lib/libtorque.so'
    server: 'quick-batch.osc.edu'
    cmd_prefix: 'PATH=/usr/local/torque-4.2.8/bin:$PATH LD_LIBRARY_PATH=/usr/local/torque-4.2.8/lib:$LD_LIBRARY_PATH'
